version: "3.7"

services:
  backend_main:
    image: backend_main
    build:
      context: ./backend/Services/Main
      dockerfile: App.API/Dockerfile.build
    container_name: plus254_backend_main
    ports:
      - 8086:80
      - 8087:443
    volumes:
      - "./mounts/backend_main/Logs:/app/Logs"
      - "./mounts/backend_main/SQL:/app/SQL"
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      plus254_network:

  backend_users:
    image: backend_users
    build:
      context: ./backend/Services/Users
      dockerfile: App.API/Dockerfile.build
    container_name: plus254_backend_users
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8088:80
      - 8089:443
    volumes:
      - "./mounts/backend_users/Logs:/app/Logs"
      - "./mounts/backend_users/SQL:/app/SQL"
    networks:
      plus254_network:

  frontend:
    image: frontend
    depends_on:
      - backend_main
      - backend_users
    build:
      context: ./frontend
      dockerfile: Dockerfile.build
    container_name: plus254_frontend
    ports:
      - 5000:80
    networks:
      plus254_network:

networks:
  plus254_network:
    driver: bridge
